### ISSUE TITLE
Not compiling SWBNLP

### ISSUE THREAD

**Issue by SergioMartinezP** [SemanticWebBuilder/SWBNLP#3]
The SWBNLP is not compiling showing the next error:
```
ERROR] Failed to execute goal on project SWBNLP: Could not resolve dependencies for project org.semanticwb:SWBNLP:jar:5.0-SNAPSHOT: Failure to find com.github.SemanticWebBuilder:SWBSearch:jar:master-5.0.0-alpha.2-g10cc708-1 in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced -> [Help 1]
```

Seems that something is wrong in the new pom

**Comment by haxdai** [comment]
@SergioMartinezP podrías provar con 

```sh
mvn package -U
```
para que te actualice el cache de maven?

**Comment by SergioMartinezP** [comment]
con -U -e para mostrar el error me dice:

```
[ERROR] Failed to execute goal on project SWBNLP: Could not resolve dependencies for project org.semanticwb:SWBNLP:jar:5.0-SNAPSHOT: Could not find artifact com.github.SemanticWebBuilder:SWBSearch:jar:master-5.0.0-alpha.2-g10cc708-1 in jitpack.io (https://jitpack.io) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project SWBNLP: Could not resolve dependencies for project org.semanticwb:SWBNLP:jar:5.0-SNAPSHOT: Could not find artifact com.github.SemanticWebBuilder:SWBSearch:jar:master-5.0.0-alpha.2-g10cc708-1 in jitpack.io (https://jitpack.io)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:220)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:257)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.semanticwb:SWBNLP:jar:5.0-SNAPSHOT: Could not find artifact com.github.SemanticWebBuilder:SWBSearch:jar:master-5.0.0-alpha.2-g10cc708-1 in jitpack.io (https://jitpack.io)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 22 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact com.github.SemanticWebBuilder:SWBSearch:jar:master-5.0.0-alpha.2-g10cc708-1 in jitpack.io (https://jitpack.io)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
	... 23 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact com.github.SemanticWebBuilder:SWBSearch:jar:master-5.0.0-alpha.2-g10cc708-1 in jitpack.io (https://jitpack.io)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 24 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.github.SemanticWebBuilder:SWBSearch:jar:master-5.0.0-alpha.2-g10cc708-1 in jitpack.io (https://jitpack.io)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 26 more
```

**Comment by SergioMartinezP** [comment]
con -Dlocal=true compiló, pero por qué es que falla un man normal de código recién descargado?

**Comment by haxdai** [comment]
Falló la compilación en jitpack de la dependencia, excedió el tiempo para compilación y no generó el artefacto. Reviso los perfiles para determinar si dejamos la construcción local como perfil por defecto.

[SWBSearch](https://jitpack.io/#SemanticWebBuilder/SWBSearch)

**Comment by haxdai** [comment]
@SergioMartinezP devolví la compilación local como perfil por defecto en todos los proyectos. Un <code>mvn package</code> utilizará los proyectos descargados para construir SWB. Si se desea usar jitpack para resolver dependencias deberá usarse <code>mvn package -Djitpack=true</code>. Se elimina la bandera **local**.
